"""Data models for the rolling market-state classifier (spec §8 / §13.9, Phase 9).

DaySnapshot  — one trading day's worth of market-breadth data.
MarketStateFeatures — aggregate rolling features computed from N snapshots.

spec §8: HOT/COLD/REHAB state-detection heuristics.
spec §13.9: rolling-feature proxy for gestalt market judgment.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from decimal import Decimal


@dataclass(frozen=True)
class DaySnapshot:
    """Breadth data for one trading day — fed from the scanner + own ledger.

    Callers record one snapshot per trading day (end-of-day or intraday
    final state).  The classifier uses a rolling window of these.

    Fields track the spec §8 heuristics:
    - count_gt100pct   → "multiple names up 100%%+ with float <5M"
    - count_tiny_float → small-float names active (proxy for HOT texture)
    - gapper_count / gapper_followthrough_count → follow-through rate
    - winner_gain_sum / winner_count → avg green day size
    - breakout_count / breakout_success_count → breakout success rate

    spec §8 / §13.9.
    """

    day: date

    # ── Big-mover counts ──────────────────────────────────────────────────
    count_gt100pct: int = 0           # names with intraday move > 100 %%
    count_tiny_float: int = 0         # names with float < 5 M active today

    # ── Gapper follow-through ─────────────────────────────────────────────
    gapper_count: int = 0             # total Tier-A gappers scanned today
    gapper_followthrough_count: int = 0  # gappers that broke PM high & held

    # ── Winner/loser size ─────────────────────────────────────────────────
    winner_count: int = 0             # names that closed above open
    winner_gain_sum: Decimal = field(default_factory=lambda: Decimal("0"))
    loser_count: int = 0              # names that closed below open
    loser_loss_sum: Decimal = field(default_factory=lambda: Decimal("0"))

    # ── Breakout success rate (own trade ledger) ───────────────────────────
    breakout_count: int = 0           # entries generated by strategy engine
    breakout_success_count: int = 0   # entries that hit target before stop


@dataclass(frozen=True)
class MarketStateFeatures:
    """Aggregate rolling features from a window of DaySnapshots.

    All rates are in [0, 1]; counts are raw.  None means insufficient data.

    spec §8 / §13.9.
    """

    days_in_window: int = 0

    # Fraction of gappers that broke PM high and held (HOT signal if high)
    gapper_follow_through: Decimal | None = None

    # Fraction of entries that hit their targets (HOT signal if high)
    breakout_success_rate: Decimal | None = None

    # Avg winner day %%gain as a fraction (e.g., 0.30 = 30 %%)
    avg_green_size: Decimal | None = None

    # Avg loser day %%loss as a fraction (e.g., 0.08 = 8 %%)
    avg_red_size: Decimal | None = None

    # Count of >100%% moves over the window (spec §8 HOT: "multiple names up 100%%+")
    count_gt100pct: int = 0

    # Count of tiny-float (<5 M) names active over the window
    count_tiny_float: int = 0
